local_dag_path: ""
airflow:
  dags:
    persistence:
      # Enable persistent volume for storing dags
      enabled: true
      ## the name of an existing PVC to use
      existingClaim: airflow-dags-pvc
      ## optional subpath for dag volume mount
      subPath: ~